name: hola_academy
description: "Master swimming with ease through personalized lessons, progress
  tracking, and expert guidance - all in one app!"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  cupertino_icons: ^1.0.8
  dropdown_button2: ^2.3.9
  easy_date_timeline: ^2.0.6
  fl_chart: ^0.70.2
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  image_picker: ^1.1.2
  qr_code_scanner: ^1.0.1
  scroll_snap_list: ^0.9.1
  syncfusion_flutter_calendar: ^28.1.39
  table_calendar: ^3.1.3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/onboarding/
    - assets/images/
    - assets/icons/
    - assets/social/
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
