// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHBGduGnmU2J9YN4W13x79fSQ1LB3JZZ8',
    appId: '1:529284234906:web:aa60198e864c9287a32923',
    messagingSenderId: '529284234906',
    projectId: 'hola-academy',
    authDomain: 'hola-academy.firebaseapp.com',
    storageBucket: 'hola-academy.firebasestorage.app',
    measurementId: 'G-7QBKYKBTEV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6DgVuMVTgEvzuPh1TVdCec37AilZvMeE',
    appId: '1:529284234906:android:901448d95a222485a32923',
    messagingSenderId: '529284234906',
    projectId: 'hola-academy',
    storageBucket: 'hola-academy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC69yZ7KfO31zWv0yMZAeHtEbBizMPpNZ0',
    appId: '1:529284234906:ios:931317bd3cd5fb28a32923',
    messagingSenderId: '529284234906',
    projectId: 'hola-academy',
    storageBucket: 'hola-academy.firebasestorage.app',
    iosBundleId: 'com.example.holaAcademy',
  );
}
